# Generated by Django 2.2 on 2019-05-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190511_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='followers',
            new_name='follows',
        ),
        migrations.AlterField(
            model_name='follows',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='follows', to='users.User'),
        ),
    ]
