# Generated by Django 2.2 on 2019-05-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190512_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follows',
            field=models.ManyToManyField(related_name='following', to='users.User'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
