# Generated by Django 2.2 on 2019-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190512_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='users.User'),
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
